services:
  - type: web
    name: django-web-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn student_mgmt_full.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: student_mgmt_full.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-app.onrender.com
g